# Generated by Django 4.2.6 on 2023-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=11)),
                ('parent_phone', models.CharField(max_length=11)),
                ('grade', models.CharField(choices=[('pre_eng', 'pre_eng'), ('ics_stat', 'ics_stat'), ('ics_cs', 'ics_cs'), ('pre_med', 'pre_med')], max_length=10)),
                ('subjects', models.ManyToManyField(to='studentManager.subject')),
            ],
        ),
    ]
