# Generated by Django 4.2.6 on 2023-10-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
