# Generated by Django 4.2.6 on 2023-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManager', '0002_remove_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('I', '1'), ('II', '2')], default='I', max_length=10),
        ),
    ]
